sudo: required
services:
  - docker

language: python
python:
  - "2.7"

env:
    global:
        - DOCKER_VERSION=17.06.2~ce-0~ubuntu
        - LONG_TESTS=1

before_install:
  - sudo apt-cache madison docker-ce
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-ce=${DOCKER_VERSION}
  - docker version

install:
  - pip install -r requirements.txt
  - pip install coveralls dockerman
  - pip install .

script:
  nosetests --with-coverage --cover-package=weavery

after_success:
  coveralls