dev:
  apt:
    - libxml2-dev
    - libxslt1-dev
    
  pip:
    - check-manifest
    - coverage
    - detox
    - dockerman>=0.1.1
    - fmap
    - lxml
    - nose
    - pip-tools
    - Sphinx
    - twine
    - tox
    - xunitmerge

prod:
  pip:
    - fabric